---
name: pynmeagps bug report

about: Create a report to help us improve

title: ''

labels: ''

assignees: semuadmin

---

# pynmeagps Bug Report Template

**NB**: Please raise any general queries in the [pynmeagps Discussions Channels](https://github.com/semuconsulting/pynmeagps/discussions) in the first instance.

**Describe the bug**

A clear and concise description of what the bug is.

Please specify the pynmeagps version (`>>> pynmeagps.version`) and, where possible, include:
- The **complete** Python script.
- The error message and full traceback.
- A binary / hexadecimal dump of the incoming NMEA data stream (e.g. from PuTTY or screen).

**To Reproduce**

Steps to reproduce the behaviour:
1. Any relevant device configuration (if other than factory defaults).
2. Any causal NMEA command input(s).

**Expected Behavior**

A clear and concise description of what you expected to happen.

**Desktop (please complete the following information):**

- The operating system you're using [e.g. Windows 11, MacOS Sequoia, Ubuntu Noble]
- The version of Python you're using (e.g. Python 3.12.4)
- The type of serial connection [e.g. USB, UART1]

**GNSS/GPS Device (please complete the following information as best you can):**

- Device Model/Generation: [e.g. u-blox ZED-F9P]
- Firmware Version: [e.g. HPG 1.32]
- Protocol: [e.g. 32.00]
 
This information is typically output by the device at startup via a series of NMEA TXT messages. 

**Additional context**

Add any other context about the problem here.
